# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BINARY_DEB "OFF")
set(CPACK_BINARY_FREEBSD "OFF")
set(CPACK_BINARY_IFW "OFF")
set(CPACK_BINARY_NSIS "OFF")
set(CPACK_BINARY_RPM "OFF")
set(CPACK_BINARY_STGZ "ON")
set(CPACK_BINARY_TBZ2 "OFF")
set(CPACK_BINARY_TGZ "ON")
set(CPACK_BINARY_TXZ "OFF")
set(CPACK_BINARY_TZ "ON")
set(CPACK_BUILD_SOURCE_DIRS "/home/duncan/Desktop/git/munt/munt/mt32emu_qt;/home/duncan/Desktop/git/munt/munt/mt32emu_qt")
set(CPACK_CMAKE_GENERATOR "Unix Makefiles")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEBIAN_PACKAGE_HOMEPAGE "http://munt.sourceforge.net/")
set(CPACK_DEBIAN_PACKAGE_SECTION "sound")
set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS "ON")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "/usr/share/cmake-3.25/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "mt32emu-qt built using CMake")
set(CPACK_GENERATOR "STGZ;TGZ;TZ")
set(CPACK_INSTALL_CMAKE_PROJECTS "/home/duncan/Desktop/git/munt/munt/mt32emu_qt;mt32emu-qt;ALL;/")
set(CPACK_INSTALL_PREFIX "/usr/local")
set(CPACK_MODULE_PATH "/home/duncan/Desktop/git/munt/munt/mt32emu_qt/cmake;/usr/lib/x86_64-linux-gnu/cmake/Qt6;/usr/lib/x86_64-linux-gnu/cmake/Qt6/3rdparty/extra-cmake-modules/find-modules;/usr/lib/x86_64-linux-gnu/cmake/Qt6/3rdparty/kwin")
set(CPACK_NSIS_DISPLAY_NAME "mt32emu-qt 1.11.1")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_PACKAGE_NAME "mt32emu-qt 1.11.1")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OBJCOPY_EXECUTABLE "/usr/bin/objcopy")
set(CPACK_OBJDUMP_EXECUTABLE "/usr/bin/objdump")
set(CPACK_OUTPUT_CONFIG_FILE "/home/duncan/Desktop/git/munt/munt/mt32emu_qt/CPackConfig.cmake")
set(CPACK_PACKAGE_CONTACT "sergm@muntemu.org")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/home/duncan/Desktop/git/munt/munt/mt32emu_qt/info.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Main MT-32 emulation application using libmt32emu")
set(CPACK_PACKAGE_EXECUTABLES "mt32emu-qt;Munt MT-32 Sound Module Emulator")
set(CPACK_PACKAGE_FILE_NAME "mt32emu-qt-1.11.1")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "mt32emu-qt 1.11.1")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "mt32emu-qt 1.11.1")
set(CPACK_PACKAGE_NAME "mt32emu-qt")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "muntemu.org")
set(CPACK_PACKAGE_VERSION "1.11.1")
set(CPACK_PACKAGE_VERSION_MAJOR "1")
set(CPACK_PACKAGE_VERSION_MINOR "11")
set(CPACK_PACKAGE_VERSION_PATCH "1")
set(CPACK_READELF_EXECUTABLE "/usr/bin/readelf")
set(CPACK_RESOURCE_FILE_LICENSE "/home/duncan/Desktop/git/munt/munt/mt32emu_qt/COPYING.txt")
set(CPACK_RESOURCE_FILE_README "/home/duncan/Desktop/git/munt/munt/mt32emu_qt/README.md")
set(CPACK_RESOURCE_FILE_WELCOME "/usr/share/cmake-3.25/Templates/CPack.GenericWelcome.txt")
set(CPACK_RPM_EXCLUDE_FROM_AUTO_FILELIST_ADDITION "/usr/local/share/icons/hicolor/16x16;/usr/local/share/icons/hicolor/16x16/apps;/usr/local/share/icons/hicolor/24x24;/usr/local/share/icons/hicolor/24x24/apps;/usr/local/share/icons/hicolor/32x32;/usr/local/share/icons/hicolor/32x32/apps;/usr/local/share/icons/hicolor/48x48;/usr/local/share/icons/hicolor/48x48/apps;/usr/local/share/icons/hicolor/64x64;/usr/local/share/icons/hicolor/64x64/apps;/usr/local/share/icons/hicolor/72x72;/usr/local/share/icons/hicolor/72x72/apps;/usr/local/share/icons/hicolor/96x96;/usr/local/share/icons/hicolor/96x96/apps;/usr/local/share/icons/hicolor/128x128;/usr/local/share/icons/hicolor/128x128/apps;/usr/local/share/icons/hicolor/256x256;/usr/local/share/icons/hicolor/256x256/apps;/usr/local/share/applications;/usr/local/share/icons;/usr/local/share/icons/hicolor")
set(CPACK_RPM_PACKAGE_GROUP "Audio/Emulators")
set(CPACK_RPM_PACKAGE_LICENSE "GPLv3+")
set(CPACK_RPM_PACKAGE_URL "http://munt.sourceforge.net/")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_GENERATOR "TGZ")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/home/duncan/Desktop/git/munt/munt/mt32emu_qt/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "mt32emu-qt-1.11.1")
set(CPACK_SOURCE_STRIP_FILES "TRUE")
set(CPACK_STRIP_FILES "TRUE")
set(CPACK_SYSTEM_NAME "Linux")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "Linux")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/home/duncan/Desktop/git/munt/munt/mt32emu_qt/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
